server {
    listen 80;

    # Der Pfad, in den wir die 'dist'-Dateien im Dockerfile kopiert haben
    root /usr/share/nginx/html;
    index index.html;

    location / {
        # Wichtig für Single-Page-Anwendungen
        try_files $uri $uri/ /index.html;
    }
}
